/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.*;

/**
 *
 * @author sbf
 */
public class NewAlienWindow extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form PasswordWindow
     */
    public NewAlienWindow(InfDB idb) {

        initComponents();
        this.idb = idb;
        fillComboBoxAgent();
        fillComboBoxArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlien = new javax.swing.JPanel();
        comboBoxAgent = new javax.swing.JComboBox<>();
        textFieldName = new javax.swing.JTextField();
        textFieldTelephone = new javax.swing.JTextField();
        textFieldPassword = new javax.swing.JPasswordField();
        labelAgent = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        comboBoxArea = new javax.swing.JComboBox<>();
        labelArea = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelNewPassword = new javax.swing.JLabel();
        buttonRegisterNewAlien = new javax.swing.JButton();
        textFieldRegistration = new javax.swing.JTextField();
        labelRegistration = new javax.swing.JLabel();
        imageAlien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelAlien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelAgent.setText("Ansvarig agent");

        labelPassword.setText("Lösenord");

        labelArea.setText("Tillhörande plats");

        labelUsername.setText("Namn");

        labelNewPassword.setText("Telefon");

        buttonRegisterNewAlien.setText("Registrera");
        buttonRegisterNewAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterNewAlienActionPerformed(evt);
            }
        });

        labelRegistration.setText("Registreringsdatum");

        imageAlien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/outer-space-alien.png"))); // NOI18N

        javax.swing.GroupLayout panelAlienLayout = new javax.swing.GroupLayout(panelAlien);
        panelAlien.setLayout(panelAlienLayout);
        panelAlienLayout.setHorizontalGroup(
            panelAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlienLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(panelAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRegistration)
                    .addGroup(panelAlienLayout.createSequentialGroup()
                        .addComponent(labelUsername)
                        .addGap(64, 64, 64)
                        .addComponent(imageAlien))
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNewPassword)
                    .addGroup(panelAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelArea)
                        .addComponent(comboBoxAgent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRegisterNewAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        panelAlienLayout.setVerticalGroup(
            panelAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUsername)
                    .addComponent(imageAlien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNewPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(labelRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRegisterNewAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        textFieldName.getAccessibleContext().setAccessibleName("");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterNewAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterNewAlienActionPerformed

        if (Validation.isNotEmpty(textFieldName, textFieldPassword, textFieldTelephone)) {

            // Hämtar in alla nödvändiga textfält från användaren.
            String name = textFieldName.getText();
            String password = textFieldPassword.getText();
            String telephone = textFieldTelephone.getText();
            String registration = textFieldRegistration.getText();
            int agent = Integer.parseInt(comboBoxAgent.getSelectedItem().toString());
            int area = Integer.parseInt(comboBoxArea.getSelectedItem().toString());

            try {
                String fetchAutoId = idb.getAutoIncrement("ALIEN", "ALIEN_ID");
                int autoId = Integer.parseInt(fetchAutoId);
                idb.insert("INSERT INTO ALIEN VALUES ('" + autoId + "','" + registration + "','" + name + "','" + password + "'," + telephone + ",'" + area + "','" + agent + "')");
                JOptionPane.showConfirmDialog(null, "Registrering av ny Alien lyckades!");
            } catch (InfException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ett fel inträffade!" + e);
            }
        }
    }//GEN-LAST:event_buttonRegisterNewAlienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fillComboBoxAgent() {
        try {
            ArrayList<String> names = idb.fetchColumn("SELECT AGENT_ID FROM AGENT;");
            for (int i = 0; i < names.size(); i++) {
                comboBoxAgent.addItem(names.get(i));
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void fillComboBoxArea() {
        try {
            ArrayList<String> area = idb.fetchColumn("SELECT PLATS_ID FROM PLATS;");
            for (int i = 0; i < area.size(); i++) {
                comboBoxArea.addItem(area.get(i));
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegisterNewAlien;
    private javax.swing.JComboBox<String> comboBoxAgent;
    private javax.swing.JComboBox<String> comboBoxArea;
    private javax.swing.JLabel imageAlien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelAgent;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegistration;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelAlien;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldRegistration;
    private javax.swing.JTextField textFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
